local ADDON, ns = ...

-- Generated by ./scripts/bake-debuffs.sh. Do not hand edit.
--
-- The auras a player class puts on a mob, and the aura a spell or a talent
-- leaves when it is not that aura itself. UnitFrames/Book.lua reads these for
-- the debuff row on the enemy bars: the name box searches AURAS, a spell
-- dragged onto the row is looked up in LEADS, and a talent dragged out of the
-- talent window in TALENTS. So the Improved Hamstring talent becomes the root
-- it procs and the Deep Wounds talent becomes the Deep Wound bleed.
--
-- Nothing here was typed. SkillLine and SkillLineAbility say which spells a
-- class casts, Talent adds every rank of every talent, and SpellEffect says
-- which of those puts an aura on an enemy and which casts another spell. One id
-- per name, the lowest, because the row matches on the name and rank 1 stands
-- for every rank. The names beside the ids are the English ones the bake read;
-- the addon asks the client for its own.

ns.DebuffData = {}

ns.DebuffData.AURAS = {
	18118, -- Aftermath
	19434, -- Aimed Shot
	5143, -- Arcane Missiles
	31935, -- Avenger's Shield
	710, -- Banish
	5211, -- Bash
	3674, -- Black Arrow
	15269, -- Blackout
	11113, -- Blast Wave
	2094, -- Blind
	356110, -- Blood Corruption
	30069, -- Blood Frenzy
	25999, -- Boar Charge
	5209, -- Challenging Roar
	1161, -- Challenging Shout
	7922, -- Charge Stun
	44041, -- Chastise
	1833, -- Cheap Shot
	6136, -- Chilled
	12809, -- Concussion Blow
	35101, -- Concussive Barrage
	5116, -- Concussive Shot
	120, -- Cone of Cold
	172, -- Corruption
	19306, -- Counterattack
	18469, -- Counterspell - Silenced
	980, -- Curse of Agony
	603, -- Curse of Doom
	18223, -- Curse of Exhaustion
	1010, -- Curse of Idiocy
	704, -- Curse of Recklessness
	1714, -- Curse of Tongues
	702, -- Curse of Weakness
	1490, -- Curse of the Elements
	33786, -- Cyclone
	29703, -- Dazed
	26679, -- Deadly Throw
	6789, -- Death Coil
	12721, -- Deep Wound
	99, -- Demoralizing Roar
	1160, -- Demoralizing Shout
	2944, -- Devouring Plague
	676, -- Disarm
	31661, -- Dragon's Breath
	689, -- Drain Life
	5138, -- Drain Mana
	1120, -- Drain Soul
	339, -- Entangling Roots
	19185, -- Entrapment
	8647, -- Expose Armor
	34501, -- Expose Weakness
	770, -- Faerie Fire
	16857, -- Faerie Fire (Feral)
	5782, -- Fear
	45334, -- Feral Charge Effect
	34889, -- Fire Breath
	22959, -- Fire Vulnerability
	133, -- Fireball
	8050, -- Flame Shock
	33831, -- Force of Nature
	122, -- Frost Nova
	8056, -- Frost Shock
	116, -- Frostbolt
	703, -- Garrote
	1776, -- Gouge
	6795, -- Growl
	853, -- Hammer of Justice
	1715, -- Hamstring
	16511, -- Hemorrhage
	9035, -- Hex of Weakness
	2637, -- Hibernate
	14914, -- Holy Fire
	31803, -- Holy Vengeance
	5484, -- Howl of Terror
	1130, -- Hunter's Mark
	12654, -- Ignite
	348, -- Immolate
	13797, -- Immolation Trap Effect
	12355, -- Impact
	19410, -- Improved Concussive Shot
	23694, -- Improved Hamstring
	19229, -- Improved Wing Clip
	5570, -- Insect Swarm
	20253, -- Intercept Stun
	5246, -- Intimidating Shout
	24394, -- Intimidation
	20184, -- Judgement of Justice
	20188, -- Judgement of the Crusader
	18425, -- Kick - Silenced
	408, -- Kidney Shot
	33745, -- Lacerate
	12705, -- Long Daze
	5530, -- Mace Stun Effect
	22570, -- Maim
	33878, -- Mangle (Bear)
	33876, -- Mangle (Cat)
	605, -- Mind Control
	15407, -- Mind Flay
	453, -- Mind Soothe
	33196, -- Misery
	694, -- Mocking Blow
	8921, -- Moonfire
	12294, -- Mortal Strike
	12323, -- Piercing Howl
	35387, -- Poison Spit
	118, -- Polymorph
	9005, -- Pounce
	9007, -- Pounce Bleed
	8122, -- Psychic Scream
	11366, -- Pyroblast
	18093, -- Pyroclasm
	1822, -- Rake
	772, -- Rend
	20066, -- Repentance
	12798, -- Revenge Stun
	1079, -- Rip
	14251, -- Riposte
	1943, -- Rupture
	2070, -- Sap
	1513, -- Scare Beast
	19503, -- Scatter Shot
	24583, -- Scorpid Poison
	3043, -- Scorpid Sting
	24423, -- Screech
	6358, -- Seduction
	27243, -- Seed of Corruption
	1978, -- Serpent Sting
	9484, -- Shackle Undead
	32386, -- Shadow Embrace
	15258, -- Shadow Vulnerability
	589, -- Shadow Word: Pain
	29341, -- Shadowburn
	30283, -- Shadowfury
	18498, -- Shield Bash - Silenced
	15487, -- Silence
	34490, -- Silencing Shot
	18265, -- Siphon Life
	31589, -- Slow
	2908, -- Soothe Animal
	27275, -- Soothing Kiss
	24259, -- Spell Lock
	16922, -- Starfire Stun
	10797, -- Starshards
	17364, -- Stormstrike
	20170, -- Stun
	1098, -- Subjugate Demon
	27271, -- Suffering
	7386, -- Sunder Armor
	19479, -- Tainted Blood Effect
	1515, -- Tame Beast
	355, -- Taunt
	6343, -- Thunder Clap
	2943, -- Touch of Weakness
	10326, -- Turn Evil
	2878, -- Turn Undead
	30108, -- Unstable Affliction
	15286, -- Vampiric Embrace
	34914, -- Vampiric Touch
	67, -- Vindication
	3034, -- Viper Sting
	2974, -- Wing Clip
	12579, -- Winter's Chill
	19386, -- Wyvern Sting
}

ns.DebuffData.LEADS = {
	[100] = 7922, -- Charge, Charge Stun
	[168] = 6136, -- Frost Armor, Chilled
	[6178] = 7922, -- Charge, Charge Stun
	[7300] = 6136, -- Frost Armor, Chilled
	[7301] = 6136, -- Frost Armor, Chilled
	[7302] = 6136, -- Ice Armor, Chilled
	[7320] = 6136, -- Ice Armor, Chilled
	[7371] = 25999, -- Charge, Boar Charge
	[9452] = 67, -- Vindication, Vindication
	[10219] = 6136, -- Ice Armor, Chilled
	[10220] = 6136, -- Ice Armor, Chilled
	[11095] = 22959, -- Improved Scorch, Fire Vulnerability
	[11103] = 12355, -- Impact, Impact
	[11180] = 12579, -- Winter's Chill, Winter's Chill
	[11255] = 18469, -- Improved Counterspell, Counterspell - Silenced
	[11578] = 7922, -- Charge, Charge Stun
	[12284] = 5530, -- Mace Specialization, Mace Stun Effect
	[12289] = 23694, -- Improved Hamstring, Improved Hamstring
	[12311] = 18498, -- Improved Shield Bash, Shield Bash - Silenced
	[12357] = 12355, -- Impact, Impact
	[12358] = 12355, -- Impact, Impact
	[12359] = 12355, -- Impact, Impact
	[12360] = 12355, -- Impact, Impact
	[12598] = 18469, -- Improved Counterspell, Counterspell - Silenced
	[12668] = 23694, -- Improved Hamstring, Improved Hamstring
	[12701] = 5530, -- Mace Specialization, Mace Stun Effect
	[12702] = 5530, -- Mace Specialization, Mace Stun Effect
	[12703] = 5530, -- Mace Specialization, Mace Stun Effect
	[12704] = 5530, -- Mace Specialization, Mace Stun Effect
	[12797] = 12798, -- Improved Revenge, Revenge Stun
	[12799] = 12798, -- Improved Revenge, Revenge Stun
	[12800] = 12798, -- Improved Revenge, Revenge Stun
	[12834] = 12721, -- Deep Wounds, Deep Wound
	[12849] = 12721, -- Deep Wounds, Deep Wound
	[12867] = 12721, -- Deep Wounds, Deep Wound
	[12872] = 22959, -- Improved Scorch, Fire Vulnerability
	[12873] = 22959, -- Improved Scorch, Fire Vulnerability
	[12958] = 18498, -- Improved Shield Bash, Shield Bash - Silenced
	[13709] = 5530, -- Mace Specialization, Mace Stun Effect
	[13754] = 18425, -- Improved Kick, Kick - Silenced
	[13800] = 5530, -- Mace Specialization, Mace Stun Effect
	[13801] = 5530, -- Mace Specialization, Mace Stun Effect
	[13802] = 5530, -- Mace Specialization, Mace Stun Effect
	[13803] = 5530, -- Mace Specialization, Mace Stun Effect
	[13867] = 18425, -- Improved Kick, Kick - Silenced
	[15257] = 15258, -- Shadow Weaving, Shadow Vulnerability
	[15268] = 15269, -- Blackout, Blackout
	[15323] = 15269, -- Blackout, Blackout
	[15324] = 15269, -- Blackout, Blackout
	[15325] = 15269, -- Blackout, Blackout
	[15326] = 15269, -- Blackout, Blackout
	[15331] = 15258, -- Shadow Weaving, Shadow Vulnerability
	[15332] = 15258, -- Shadow Weaving, Shadow Vulnerability
	[15333] = 15258, -- Shadow Weaving, Shadow Vulnerability
	[15334] = 15258, -- Shadow Weaving, Shadow Vulnerability
	[16689] = 339, -- Nature's Grasp, Entangling Roots
	[16810] = 339, -- Nature's Grasp, Entangling Roots
	[16811] = 339, -- Nature's Grasp, Entangling Roots
	[16812] = 339, -- Nature's Grasp, Entangling Roots
	[16813] = 339, -- Nature's Grasp, Entangling Roots
	[16850] = 16922, -- Celestial Focus, Starfire Stun
	[16923] = 16922, -- Celestial Focus, Starfire Stun
	[16924] = 16922, -- Celestial Focus, Starfire Stun
	[16979] = 45334, -- Feral Charge, Feral Charge Effect
	[17329] = 339, -- Nature's Grasp, Entangling Roots
	[17793] = 15258, -- Improved Shadow Bolt, Shadow Vulnerability
	[17796] = 15258, -- Improved Shadow Bolt, Shadow Vulnerability
	[17801] = 15258, -- Improved Shadow Bolt, Shadow Vulnerability
	[17802] = 15258, -- Improved Shadow Bolt, Shadow Vulnerability
	[17803] = 15258, -- Improved Shadow Bolt, Shadow Vulnerability
	[17877] = 29341, -- Shadowburn, Shadowburn
	[18119] = 18118, -- Aftermath, Aftermath
	[18120] = 18118, -- Aftermath, Aftermath
	[18121] = 18118, -- Aftermath, Aftermath
	[18122] = 18118, -- Aftermath, Aftermath
	[18123] = 18118, -- Aftermath, Aftermath
	[18867] = 29341, -- Shadowburn, Shadowburn
	[18868] = 29341, -- Shadowburn, Shadowburn
	[18869] = 29341, -- Shadowburn, Shadowburn
	[18870] = 29341, -- Shadowburn, Shadowburn
	[18871] = 29341, -- Shadowburn, Shadowburn
	[19184] = 19185, -- Entrapment, Entrapment
	[19228] = 19229, -- Improved Wing Clip, Improved Wing Clip
	[19232] = 19229, -- Improved Wing Clip, Improved Wing Clip
	[19233] = 19229, -- Improved Wing Clip, Improved Wing Clip
	[19244] = 24259, -- Spell Lock, Spell Lock
	[19387] = 19185, -- Entrapment, Entrapment
	[19388] = 19185, -- Entrapment, Entrapment
	[19407] = 19410, -- Improved Concussive Shot, Improved Concussive Shot
	[19412] = 19410, -- Improved Concussive Shot, Improved Concussive Shot
	[19413] = 19410, -- Improved Concussive Shot, Improved Concussive Shot
	[19414] = 19410, -- Improved Concussive Shot, Improved Concussive Shot
	[19415] = 19410, -- Improved Concussive Shot, Improved Concussive Shot
	[19478] = 19479, -- Tainted Blood, Tainted Blood Effect
	[19577] = 24394, -- Intimidation, Intimidation
	[19647] = 24259, -- Spell Lock, Spell Lock
	[19655] = 19479, -- Tainted Blood, Tainted Blood Effect
	[19656] = 19479, -- Tainted Blood, Tainted Blood Effect
	[19660] = 19479, -- Tainted Blood, Tainted Blood Effect
	[20164] = 20170, -- Seal of Justice, Stun
	[20252] = 20253, -- Intercept, Intercept Stun
	[20616] = 20253, -- Intercept, Intercept Stun
	[20617] = 20253, -- Intercept, Intercept Stun
	[23695] = 23694, -- Improved Hamstring, Improved Hamstring
	[25272] = 20253, -- Intercept, Intercept Stun
	[25275] = 20253, -- Intercept, Intercept Stun
	[26016] = 67, -- Vindication, Vindication
	[26021] = 67, -- Vindication, Vindication
	[26177] = 25999, -- Charge, Boar Charge
	[26178] = 25999, -- Charge, Boar Charge
	[26179] = 25999, -- Charge, Boar Charge
	[26201] = 25999, -- Charge, Boar Charge
	[27009] = 339, -- Nature's Grasp, Entangling Roots
	[27124] = 6136, -- Ice Armor, Chilled
	[27263] = 29341, -- Shadowburn, Shadowburn
	[27280] = 19479, -- Tainted Blood, Tainted Blood Effect
	[27685] = 25999, -- Charge, Boar Charge
	[28592] = 12579, -- Winter's Chill, Winter's Chill
	[28593] = 12579, -- Winter's Chill, Winter's Chill
	[28594] = 12579, -- Winter's Chill, Winter's Chill
	[28595] = 12579, -- Winter's Chill, Winter's Chill
	[29704] = 29703, -- Shield Bash, Dazed
	[29836] = 30069, -- Blood Frenzy, Blood Frenzy
	[29859] = 30069, -- Blood Frenzy, Blood Frenzy
	[30151] = 20253, -- Intercept, Intercept Stun
	[30194] = 20253, -- Intercept, Intercept Stun
	[30198] = 20253, -- Intercept, Intercept Stun
	[30546] = 29341, -- Shadowburn, Shadowburn
	[31124] = 29703, -- Blade Twisting, Dazed
	[31126] = 29703, -- Blade Twisting, Dazed
	[31895] = 20170, -- Seal of Justice, Stun
	[32385] = 32386, -- Shadow Embrace, Shadow Embrace
	[32387] = 32386, -- Shadow Embrace, Shadow Embrace
	[32392] = 32386, -- Shadow Embrace, Shadow Embrace
	[32393] = 32386, -- Shadow Embrace, Shadow Embrace
	[32394] = 32386, -- Shadow Embrace, Shadow Embrace
	[33191] = 33196, -- Misery, Misery
	[33192] = 33196, -- Misery, Misery
	[33193] = 33196, -- Misery, Misery
	[33194] = 33196, -- Misery, Misery
	[33195] = 33196, -- Misery, Misery
	[34500] = 34501, -- Expose Weakness, Expose Weakness
	[34502] = 34501, -- Expose Weakness, Expose Weakness
	[34503] = 34501, -- Expose Weakness, Expose Weakness
	[35100] = 35101, -- Concussive Barrage, Concussive Barrage
	[35102] = 35101, -- Concussive Barrage, Concussive Barrage
	[35103] = 35101, -- Concussive Barrage, Concussive Barrage
}

ns.DebuffData.TALENTS = {
	[25] = 22959, -- Fire Vulnerability
	[29] = 11366, -- Pyroblast
	[30] = 12355, -- Impact
	[32] = 11113, -- Blast Wave
	[68] = 12579, -- Winter's Chill
	[88] = 18469, -- Counterspell - Silenced
	[121] = 12721, -- Deep Wound
	[125] = 5530, -- Mace Stun Effect
	[129] = 23694, -- Improved Hamstring
	[135] = 12294, -- Mortal Strike
	[147] = 12798, -- Revenge Stun
	[149] = 18498, -- Shield Bash - Silenced
	[152] = 12809, -- Concussion Blow
	[160] = 12323, -- Piercing Howl
	[184] = 5530, -- Mace Stun Effect
	[206] = 18425, -- Kick - Silenced
	[301] = 14251, -- Riposte
	[461] = 15258, -- Shadow Vulnerability
	[464] = 15269, -- Blackout
	[484] = 15286, -- Vampiric Embrace
	[501] = 15407, -- Mind Flay
	[541] = 15487, -- Silence
	[681] = 16511, -- Hemorrhage
	[761] = 339, -- Entangling Roots
	[784] = 16922, -- Starfire Stun
	[788] = 5570, -- Insect Swarm
	[804] = 45334, -- Feral Charge Effect
	[901] = 17364, -- Stormstrike
	[944] = 15258, -- Shadow Vulnerability
	[963] = 29341, -- Shadowburn
	[982] = 18118, -- Aftermath
	[1041] = 18265, -- Siphon Life
	[1081] = 18223, -- Curse of Exhaustion
	[1162] = 16857, -- Faerie Fire (Feral)
	[1304] = 19185, -- Entrapment
	[1305] = 19229, -- Improved Wing Clip
	[1312] = 19306, -- Counterattack
	[1325] = 19386, -- Wyvern Sting
	[1341] = 19410, -- Improved Concussive Shot
	[1345] = 19434, -- Aimed Shot
	[1351] = 35101, -- Concussive Barrage
	[1353] = 19503, -- Scatter Shot
	[1387] = 24394, -- Intimidation
	[1441] = 20066, -- Repentance
	[1633] = 67, -- Vindication
	[1664] = 30069, -- Blood Frenzy
	[1670] = 30108, -- Unstable Affliction
	[1676] = 30283, -- Shadowfury
	[1706] = 29703, -- Dazed
	[1729] = 31589, -- Slow
	[1735] = 31661, -- Dragon's Breath
	[1754] = 31935, -- Avenger's Shield
	[1763] = 32386, -- Shadow Embrace
	[1779] = 34914, -- Vampiric Touch
	[1787] = 33831, -- Force of Nature
	[1808] = 34490, -- Silencing Shot
	[1812] = 34501, -- Expose Weakness
	[1816] = 33196, -- Misery
}
