local ADDON, ns = ...

-- Written by scripts/bake-backdrops.sh. Do not edit: change the painting or
-- the numbers at the top of the bake, and run it again.
--
-- One entry per palette that has a painted frame. Each piece is a texture
-- and the size it is drawn at in window units; corner, top and left are the
-- frame's thickness outside the window, and fade is how far each rail and
-- corner reaches in over the floor. cover says the floor is one picture
-- drawn over the whole window, and its size is the picture's shape. A
-- palette with no entry keeps the flat window fill.

ns.Backdrops = {
	forest = {
		thickness = { left = 18, top = 16, right = 18, bottom = 16 },
		fade = 5,
		corner = 36,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-Top.tga", 100, 21 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-Bottom.tga", 100, 21 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-Left.tga", 23, 104 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-Right.tga", 23, 104 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-TopLeft.tga", 36, 36 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-TopRight.tga", 36, 36 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-BottomLeft.tga", 36, 36 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Forest-BottomRight.tga", 36, 36 },
	},
	desert = {
		thickness = { left = 22, top = 30, right = 25, bottom = 24 },
		fade = 5,
		corner = 63,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-Top.tga", 100, 35 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-Bottom.tga", 100, 29 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-Left.tga", 26, 104 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-Right.tga", 29, 104 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-TopLeft.tga", 63, 63 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-TopRight.tga", 63, 63 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-BottomLeft.tga", 63, 63 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Desert-BottomRight.tga", 63, 63 },
	},
	arcane = {
		thickness = { left = 23, top = 30, right = 23, bottom = 25 },
		fade = 5,
		corner = 63,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-Top.tga", 90, 35 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-Bottom.tga", 90, 29 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-Left.tga", 28, 66 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-Right.tga", 28, 66 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-TopLeft.tga", 63, 63 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-TopRight.tga", 63, 63 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-BottomLeft.tga", 63, 63 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Arcane-BottomRight.tga", 63, 63 },
	},
	horde = {
		thickness = { left = 23, top = 30, right = 23, bottom = 25 },
		fade = 5,
		corner = 63,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-Top.tga", 90, 35 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-Bottom.tga", 90, 29 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-Left.tga", 28, 45 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-Right.tga", 28, 45 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-TopLeft.tga", 63, 63 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-TopRight.tga", 63, 63 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-BottomLeft.tga", 63, 63 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Horde-BottomRight.tga", 63, 63 },
	},
	alliance = {
		thickness = { left = 23, top = 30, right = 23, bottom = 25 },
		fade = 5,
		corner = 63,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-Top.tga", 90, 35 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-Bottom.tga", 90, 29 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-Left.tga", 28, 45 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-Right.tga", 28, 45 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-TopLeft.tga", 63, 63 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-TopRight.tga", 63, 63 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-BottomLeft.tga", 63, 63 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Alliance-BottomRight.tga", 63, 63 },
	},
	fire = {
		thickness = { left = 29, top = 30, right = 28, bottom = 25 },
		fade = 5,
		corner = 90,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-Top.tga", 140, 35 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-Bottom.tga", 140, 30 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-Left.tga", 34, 78 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-Right.tga", 33, 78 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-TopLeft.tga", 90, 90 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-TopRight.tga", 90, 90 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-BottomLeft.tga", 90, 90 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Fire-BottomRight.tga", 90, 90 },
	},
	parchment = {
		thickness = { left = 33, top = 33, right = 33, bottom = 33 },
		fade = 5,
		corner = 45,
		cover = true,
		Middle = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-Middle.tga", 1408, 768 },
		Top = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-Top.tga", 180, 38 },
		Bottom = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-Bottom.tga", 180, 38 },
		Left = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-Left.tga", 38, 102 },
		Right = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-Right.tga", 38, 102 },
		TopLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-TopLeft.tga", 45, 45 },
		TopRight = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-TopRight.tga", 45, 45 },
		BottomLeft = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-BottomLeft.tga", 45, 45 },
		BottomRight = { "Interface\\AddOns\\WiggleUI\\Media\\Parchment-BottomRight.tga", 45, 45 },
	},
}
