local ADDON, ns = ...

-- Generated by ./bake-ui.sh. Do not hand edit: capture a layout in game with
-- /wui ui save, /reload so the game writes it to saved variables, then run
-- ./bake-ui.sh from the addon folder to rewrite this file.

ns.EditMode.SAVED = nil
