local ADDON, ns = ...

-- Generated by ./scripts/bake-defaults.sh. Do not hand edit: set the addon up
-- in game the way it should ship, /reload so the client writes its saved
-- variables, then run ./scripts/bake-defaults.sh to rewrite this file.
--
-- One entry per setting that screen answers differently from the feature that
-- owns it, the account's in the first table and the character's in the second.
-- Core\Core.lua merges them over the two registries at load and checks every
-- key against them; the header there says why this is a capture rather than an
-- edited literal per setting.

ns.Shipped = {
	adhocZoom = 1,
	buffPoint = { "TOP", "UIParent", "TOP", 0, -61 },
	buffPulse = false,
	chatFont = 17,
	chatIcon = 24,
	chatWidth = 530,
	cooldownPoint = { "BOTTOM", "UIParent", "BOTTOM", 3, 312 },
	hitsArc = 50,
	hitsDrop = 135,
	hitsLife = 1.5,
	hitsSize = 26,
	hoverSheetPoint = { "TOPRIGHT", "UIParent", "TOPRIGHT", -547, -228 },
	hoverWho = "enemy",
	lootFeedPoint = { "RIGHT", "UIParent", "RIGHT", -114, -54 },
	lootFloatHold = 2.75,
	lootFloatIcon = 44,
	lootFloatRest = 75,
	lootFloatSide = "LEFT",
	lootFloatTop = 160,
	partyMiddle = { "CENTER", "UIParent", "CENTER", 4, -421 },
	playerCastPoint = { "BOTTOM", "UIParent", "BOTTOM", 0, 99 },
	questsColumnPoint = { "TOPLEFT", "UIParent", "TOPLEFT", 19, -43 },
	questsTabs = "across",
	questsTrackerOff = true,
	raidMiddle = { "CENTER", "UIParent", "CENTER", -879, 46 },
	skinFrames = {
		player = true,
		target = true,
		tot = true,
	},
	skinPlayerPoint = { "CENTER", "UIParent", "CENTER", -456, -282 },
	standingPoint = { "CENTER", "UIParent", "CENTER", -252, -289 },
	thankWord = "Thank you!",
	tipFont = 11,
	tipLinger = 1,
	tipPoint = { "LEFT", "UIParent", "LEFT", 592, -44 },
	tipZoom = 1.6,
	windowSpots = {
		WarriorKitBags = { "TOPRIGHT", "UIParent", "TOPRIGHT", -309, -62 },
		WarriorKitBreakdown = { "TOP", "UIParent", "TOP", -313, -130 },
		WarriorKitCharacter = { "RIGHT", "UIParent", "RIGHT", -1089, 207 },
		WarriorKitClutter = { "CENTER", "UIParent", "CENTER", 122, 91 },
		WarriorKitDungeons = { "LEFT", "UIParent", "LEFT", 345, 102 },
		WarriorKitMail = { "TOPLEFT", "UIParent", "TOPLEFT", 411, -100 },
		WarriorKitMap = { "TOPLEFT", "UIParent", "TOPLEFT", 300, -59 },
		WarriorKitMerchant = { "TOP", "UIParent", "TOP", 313, -48 },
		WarriorKitOptions = { "TOPLEFT", "UIParent", "TOPLEFT", 331, -62 },
		WarriorKitPerf = { "LEFT", "UIParent", "LEFT", 83, 161 },
		WarriorKitQuests = { "TOP", "UIParent", "TOP", -367, -29 },
		WarriorKitSockets = { "TOP", "UIParent", "TOP", 269, -128 },
		WarriorKitSpellbook = { "CENTER", "UIParent", "CENTER", 413, 170 },
		WarriorKitTalents = { "TOP", "UIParent", "TOP", -77, -50 },
	},
}

ns.ShippedChar = {
	figureFacing = 0.39333312988285,
	figureSheathed = false,
}

-- One screen per mode, over the common one above. The setup lays the chosen
-- mode's screen on a profile when it finishes; see ns.ShippedAs in Core.lua.
ns.ShippedModes = {}
