#!/usr/bin/env bash
# Bakes the Edit Mode layout captured by /wui ui save into EditMode/Saved.lua.
#
# An addon cannot write files, and saved variables live in WTF, which is per
# install and does not travel. So the capture goes out through saved variables
# and comes back in here, as a file in the addon folder that a git clone or a
# copied directory carries with it.
#
#   in game     /wui ui save, then /reload
#   in a shell  ./bake-ui.sh [path/to/WTF/.../SavedVariables/WiggleUI.lua]
set -uo pipefail
# The addon is src/, this script is scripts/. Everything below is relative to
# the addon root, so land there and the paths stay as they were.
cd "$(dirname "$0")/../src"

# The addon folder is a git repo outside the game tree now, reached from each
# client through a symlink, so WTF is no longer three levels up. Both flavours
# get searched by absolute path instead. Override WOW_ROOT for another install.
WOW_ROOT="${WOW_ROOT:-$HOME/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft}"

saved="${1:-}"
if [ -z "$saved" ]; then
	[ -d "$WOW_ROOT" ] || { echo "no install at $WOW_ROOT. Set WOW_ROOT, or pass the file." >&2; exit 1; }

	# Every client the addon is linked into keeps its own saved variables, and
	# only the one you ran /wui ui save on holds a layout. So a file without a
	# capture in it is not a candidate, rather than an ambiguity to ask about.
	#
	# The test is a non-empty uiLayoutName, not the presence of uiLayout. The
	# defaults table carries uiLayout = {} and uiLayoutName = "", so every client
	# that has ever loaded the addon writes both keys out, and matching the key
	# alone matches clients that captured nothing.
	found=()
	while IFS= read -r f; do
		grep -qE '\["uiLayoutName"\] = "[^"]' "$f" && found+=("$f")
	done < <(find "$WOW_ROOT"/_*_/WTF/Account -maxdepth 3 -path '*/SavedVariables/WiggleUI.lua' 2>/dev/null | sort)

	if [ "${#found[@]}" -eq 0 ]; then
		echo "no capture under $WOW_ROOT. Log in once, /wui ui save, /reload." >&2
		exit 1
	fi
	if [ "${#found[@]}" -gt 1 ]; then
		echo "more than one client holds a capture, name the one you want:" >&2
		printf '  %s\n' "${found[@]}" >&2
		exit 1
	fi
	saved="${found[0]}"
fi

[ -r "$saved" ] || { echo "cannot read $saved" >&2; exit 1; }

lua5.1 - "$saved" EditMode/Saved.lua <<'LUA' || exit 1
local source, target = ...

-- Saved variables are Lua, so read them as Lua rather than with a regex, in a
-- table of their own so a corrupt file cannot reach anything real.
local chunk = assert(loadfile(source))
local env = {}
setfenv(chunk, env)
assert(pcall(chunk))

local db = env.WiggleUIDB
assert(type(db) == "table", "no WiggleUIDB in " .. source)

local layout = db.uiLayout
assert(type(layout) == "table" and next(layout) ~= nil,
	"nothing captured. In game: /wui ui save, then /reload, then run this again.")

local name = db.uiLayoutName
if name == nil or name == "" then
	name = layout.layoutName
end
assert(type(name) == "string" and name ~= "", "the capture has no layout name")

-- Deterministic on purpose. Keys come out sorted so re-baking an unchanged
-- layout produces a byte identical file and the diff stays readable.
local KEYWORDS = {
	["and"] = true, ["break"] = true, ["do"] = true, ["else"] = true,
	["elseif"] = true, ["end"] = true, ["false"] = true, ["for"] = true,
	["function"] = true, ["if"] = true, ["in"] = true, ["local"] = true,
	["nil"] = true, ["not"] = true, ["or"] = true, ["repeat"] = true,
	["return"] = true, ["then"] = true, ["true"] = true, ["until"] = true,
	["while"] = true,
}

local function order(a, b)
	local ta, tb = type(a), type(b)
	if ta ~= tb then
		return ta < tb
	end
	if ta == "number" or ta == "string" then
		return a < b
	end
	return tostring(a) < tostring(b)
end

local function key(k)
	if type(k) == "string" and not KEYWORDS[k] and k:match("^[A-Za-z_][A-Za-z0-9_]*$") then
		return k
	end
	if type(k) == "number" then
		return ("[%.14g]"):format(k)
	end
	return ("[%q]"):format(tostring(k))
end

local serialize

function serialize(value, indent)
	local kind = type(value)
	if kind == "string" then
		return ("%q"):format(value)
	elseif kind == "number" then
		return ("%.14g"):format(value)
	elseif kind == "boolean" then
		return tostring(value)
	elseif kind ~= "table" then
		error("a layout cannot hold a " .. kind)
	end

	local keys = {}
	for k in pairs(value) do
		keys[#keys + 1] = k
	end
	if #keys == 0 then
		return "{}"
	end
	table.sort(keys, order)

	local inner = indent .. "\t"
	local out = { "{" }
	for _, k in ipairs(keys) do
		out[#out + 1] = ("%s%s = %s,"):format(inner, key(k), serialize(value[k], inner))
	end
	out[#out + 1] = indent .. "}"
	return table.concat(out, "\n")
end

local file = assert(io.open(target, "w"))
file:write("local ADDON, ns = ...\n\n")
file:write("-- Generated by ./bake-ui.sh. Do not hand edit: capture a layout in game with\n")
file:write("-- /wui ui save, /reload so the game writes it to saved variables, then run\n")
file:write("-- ./bake-ui.sh from the addon folder to rewrite this file.\n\n")
file:write("ns.EditMode.SAVED = {\n")
file:write(("\tname = %q,\n"):format(name))
file:write(("\tstamp = %q,\n"):format(tostring(db.uiLayoutStamp or "")))
file:write(("\tlayout = %s,\n"):format(serialize(layout, "\t")))
file:write("}\n")
file:close()

io.write(("baked %q into %s\n"):format(name, target))
LUA

# Saved.lua is a Lua file in a TOC, so a bad bake is a broken addon. cwd is
# src/, and check.sh is a sibling of this script, not of the code.
../scripts/check.sh
