local ADDON, ns = ...

-- Generated by ./scripts/bake-dungeon-maps.sh. Do not hand edit.
--
-- The picture of every dungeon, as the tiles the client has for it.
--
-- Neither of these clients will answer this. The 1.15 one has no dungeon maps
-- in its map tree at all, and the 2.5 one has a hundred and four of them and
-- files art for none, so C_Map.GetMapArtLayers comes back empty on every
-- dungeon in the game. Both of them ship the tiles themselves under
-- Interface\WorldMap, twelve to a floor, and a texture is drawn by path.
--
-- So this is the join, and every part of it is read out of Blizzard's own
-- tables by scripts/bake-dungeon-maps.lua: which floors a dungeon is cut into
-- and what each is called out of UiMapGroupMember, the tiles out of
-- UiMapArtTile, and the map id each floor answers to out of the 2.5 client's
-- own UiMap, which is the id a mark you leave is filed under.
--
-- `art` is a prefix. The twelve tiles are it and one to twelve, in reading
-- order, which is the order UI/Chart.lua lays a zone's out in.

local Sheets = {}
ns.DungeonSheets = Sheets

Sheets.LAYER = { layerWidth = 1002, layerHeight = 668, tileWidth = 256, tileHeight = 256 }
Sheets.TILES = 12

Sheets.PLACES = {
	["Ragefire Chasm"] = {
		{ map = 213, name = "Ragefire Chasm", art = "interface\\worldmap\\ragefire\\ragefire1_" },
	},
	["Wailing Caverns"] = {
		{ map = 279, name = "Wailing Caverns", art = "interface\\worldmap\\wailingcaverns\\wailingcaverns1_" },
	},
	["The Deadmines"] = {
		{ map = 291, name = "The Deadmines", art = "interface\\worldmap\\thedeadmines\\thedeadmines1_" },
		{ map = 292, name = "Ironclad Cove", art = "interface\\worldmap\\thedeadmines\\thedeadmines2_" },
	},
	["Shadowfang Keep"] = {
		{ map = 310, name = "The Courtyard", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep1_" },
		{ map = 311, name = "Dining Hall", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep2_" },
		{ map = 312, name = "The Vacant Den", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep3_" },
		{ map = 313, name = "Lower Observatory", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep4_" },
		{ map = 314, name = "Upper Observatory", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep5_" },
		{ map = 315, name = "Lord Godfrey's Chamber", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep6_" },
		{ map = 316, name = "The Wall Walk", art = "interface\\worldmap\\shadowfangkeep\\shadowfangkeep7_" },
	},
	["Blackfathom Deeps"] = {
		{ map = 221, name = "The Pool of Ask'Ar", art = "interface\\worldmap\\blackfathomdeeps\\blackfathomdeeps1_" },
		{ map = 222, name = "Moonshrine Sanctum", art = "interface\\worldmap\\blackfathomdeeps\\blackfathomdeeps2_" },
		{ map = 223, name = "The Forgotten Pool", art = "interface\\worldmap\\blackfathomdeeps\\blackfathomdeeps3_" },
	},
	["The Stockade"] = {
		{ map = 225, name = "The Stockade", art = "interface\\worldmap\\thestockade\\thestockade1_" },
	},
	["Gnomeregan"] = {
		{ map = 226, name = "The Hall of Gears", art = "interface\\worldmap\\gnomeregan\\gnomeregan1_" },
		{ map = 227, name = "The Dormitory", art = "interface\\worldmap\\gnomeregan\\gnomeregan2_" },
		{ map = 228, name = "Launch Bay", art = "interface\\worldmap\\gnomeregan\\gnomeregan3_" },
		{ map = 229, name = "Tinkers' Court", art = "interface\\worldmap\\gnomeregan\\gnomeregan4_" },
	},
	["Razorfen Kraul"] = {
		{ map = 301, name = "Razorfen Kraul", art = "interface\\worldmap\\razorfenkraul\\razorfenkraul1_" },
	},
	["Scarlet Monastery"] = {
		{ map = 302, name = "Graveyard", art = "interface\\worldmap\\scarletmonastery\\scarletmonastery1_" },
		{ map = 303, name = "Library", art = "interface\\worldmap\\scarletmonastery\\scarletmonastery2_" },
		{ map = 304, name = "Armory", art = "interface\\worldmap\\scarletmonastery\\scarletmonastery3_" },
		{ map = 305, name = "Cathedral", art = "interface\\worldmap\\scarletmonastery\\scarletmonastery4_" },
	},
	["Razorfen Downs"] = {
		{ map = 300, name = "Razorfen Downs", art = "interface\\worldmap\\razorfendowns\\razorfendowns1_" },
	},
	["Uldaman"] = {
		{ map = 230, name = "Hall of the Keepers", art = "interface\\worldmap\\uldaman\\uldaman1_" },
		{ map = 231, name = "Khaz'Goroth's Seat", art = "interface\\worldmap\\uldaman\\uldaman2_" },
	},
	["Zul'Farrak"] = {
		{ map = 219, name = "Zul'Farrak", art = "interface\\worldmap\\zulfarrak\\zulfarrak" },
	},
	["Maraudon"] = {
		{ map = 280, name = "Caverns of Maraudon", art = "interface\\worldmap\\maraudon\\maraudon1_" },
		{ map = 281, name = "Zaetar's Grave", art = "interface\\worldmap\\maraudon\\maraudon2_" },
	},
	["The Temple of Atal'Hakkar"] = {
		{ map = 220, name = "The Temple of Atal'Hakkar", art = "interface\\worldmap\\thetempleofatalhakkar\\thetempleofatalhakkar1_" },
	},
	["Blackrock Depths"] = {
		{ map = 242, name = "Detention Block", art = "interface\\worldmap\\blackrockdepths\\blackrockdepths1_" },
		{ map = 243, name = "Shadowforge City", art = "interface\\worldmap\\blackrockdepths\\blackrockdepths2_" },
	},
	["Lower Blackrock Spire"] = {
		{ map = 250, name = "Tazz'Alor", art = "interface\\worldmap\\blackrockspire\\blackrockspire1_" },
		{ map = 251, name = "Skitterweb Tunnels", art = "interface\\worldmap\\blackrockspire\\blackrockspire2_" },
		{ map = 252, name = "Hordemar City", art = "interface\\worldmap\\blackrockspire\\blackrockspire3_" },
		{ map = 253, name = "Hall of Blackhand", art = "interface\\worldmap\\blackrockspire\\blackrockspire4_" },
		{ map = 254, name = "Halycon's Lair", art = "interface\\worldmap\\blackrockspire\\blackrockspire5_" },
		{ map = 255, name = "Chamber of Battle", art = "interface\\worldmap\\blackrockspire\\blackrockspire6_" },
	},
	["Upper Blackrock Spire"] = {
		{ map = 250, name = "Tazz'Alor", art = "interface\\worldmap\\blackrockspire\\blackrockspire1_" },
		{ map = 251, name = "Skitterweb Tunnels", art = "interface\\worldmap\\blackrockspire\\blackrockspire2_" },
		{ map = 252, name = "Hordemar City", art = "interface\\worldmap\\blackrockspire\\blackrockspire3_" },
		{ map = 253, name = "Hall of Blackhand", art = "interface\\worldmap\\blackrockspire\\blackrockspire4_" },
		{ map = 254, name = "Halycon's Lair", art = "interface\\worldmap\\blackrockspire\\blackrockspire5_" },
		{ map = 255, name = "Chamber of Battle", art = "interface\\worldmap\\blackrockspire\\blackrockspire6_" },
	},
	["Dire Maul"] = {
		{ map = 235, name = "Gordok Commons", art = "interface\\worldmap\\diremaul\\diremaul1_" },
		{ map = 236, name = "Capital Gardens", art = "interface\\worldmap\\diremaul\\diremaul2_" },
		{ map = 237, name = "Court of the Highborne", art = "interface\\worldmap\\diremaul\\diremaul3_" },
		{ map = 238, name = "Prison of Immol'Thar", art = "interface\\worldmap\\diremaul\\diremaul4_" },
		{ map = 239, name = "Warpwood Quarter", art = "interface\\worldmap\\diremaul\\diremaul5_" },
		{ map = 240, name = "The Shrine of Eldretharr", art = "interface\\worldmap\\diremaul\\diremaul6_" },
	},
	["Scholomance"] = {
		{ map = 306, name = "The Reliquary", art = "interface\\worldmap\\scholomanceold\\scholomanceold1_" },
		{ map = 307, name = "Chamber of Summoning", art = "interface\\worldmap\\scholomanceold\\scholomanceold2_" },
		{ map = 308, name = "The Upper Study", art = "interface\\worldmap\\scholomanceold\\scholomanceold3_" },
		{ map = 309, name = "Headmaster's Study", art = "interface\\worldmap\\scholomanceold\\scholomanceold4_" },
	},
	["Stratholme"] = {
		{ map = 317, name = "Crusader's Square", art = "interface\\worldmap\\stratholme\\stratholme1_" },
		{ map = 318, name = "The Gauntlet", art = "interface\\worldmap\\stratholme\\stratholme2_" },
	},
	["Hellfire Ramparts"] = {
		{ map = 347, name = "Hellfire Ramparts", art = "interface\\worldmap\\hellfireramparts\\hellfireramparts1_" },
	},
	["The Blood Furnace"] = {
		{ map = 261, name = "The Blood Furnace", art = "interface\\worldmap\\thebloodfurnace\\thebloodfurnace1_" },
	},
	["The Slave Pens"] = {
		{ map = 265, name = "The Slave Pens", art = "interface\\worldmap\\theslavepens\\theslavepens1_" },
	},
	["The Underbog"] = {
		{ map = 262, name = "The Underbog", art = "interface\\worldmap\\theunderbog\\theunderbog1_" },
	},
	["Mana-Tombs"] = {
		{ map = 272, name = "Mana-Tombs", art = "interface\\worldmap\\manatombs\\manatombs1_" },
	},
	["Auchenai Crypts"] = {
		{ map = 256, name = "Halls of the Hereafter", art = "interface\\worldmap\\auchenaicrypts\\auchenaicrypts1_" },
		{ map = 257, name = "Bridge of Souls", art = "interface\\worldmap\\auchenaicrypts\\auchenaicrypts2_" },
	},
	["Old Hillsbrad Foothills"] = {
		{ map = 274, name = "Old Hillsbrad Foothills", art = "interface\\worldmap\\cothillsbradfoothills\\cothillsbradfoothills" },
	},
	["Sethekk Halls"] = {
		{ map = 258, name = "Veil Sethekk", art = "interface\\worldmap\\sethekkhalls\\sethekkhalls1_" },
		{ map = 259, name = "Halls of Mourning", art = "interface\\worldmap\\sethekkhalls\\sethekkhalls2_" },
	},
	["The Steamvault"] = {
		{ map = 263, name = "The Steamvault", art = "interface\\worldmap\\thesteamvault\\thesteamvault1_" },
		{ map = 264, name = "The Cooling Pools", art = "interface\\worldmap\\thesteamvault\\thesteamvault2_" },
	},
	["The Black Morass"] = {
		{ map = 273, name = "The Black Morass", art = "interface\\worldmap\\cottheblackmorass\\cottheblackmorass" },
	},
	["Shadow Labyrinth"] = {
		{ map = 260, name = "Shadow Labyrinth", art = "interface\\worldmap\\shadowlabyrinth\\shadowlabyrinth1_" },
	},
	["The Shattered Halls"] = {
		{ map = 246, name = "The Shattered Halls", art = "interface\\worldmap\\theshatteredhalls\\theshatteredhalls1_" },
	},
	["The Mechanar"] = {
		{ map = 267, name = "The Mechanar", art = "interface\\worldmap\\themechanar\\themechanar1_" },
		{ map = 268, name = "Calculation Chamber", art = "interface\\worldmap\\themechanar\\themechanar2_" },
	},
	["The Botanica"] = {
		{ map = 266, name = "The Botanica", art = "interface\\worldmap\\thebotanica\\thebotanica1_" },
	},
	["The Arcatraz"] = {
		{ map = 269, name = "Stasis Block: Trion", art = "interface\\worldmap\\thearcatraz\\thearcatraz1_" },
		{ map = 270, name = "Stasis Block: Maximus", art = "interface\\worldmap\\thearcatraz\\thearcatraz2_" },
		{ map = 271, name = "Containment Core", art = "interface\\worldmap\\thearcatraz\\thearcatraz3_" },
	},
}
